- name: pan-os-configuration
  hosts: all
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:

  - name: Set ethernet1/1 as static IP (Untrusted)
    panos_interface:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      if_name: "ethernet1/1"
      mode: "layer3"
      ip: ["{pan_untrusted_ip}/24"]
      enable_dhcp: false
      operation: "update"
      commit: False

  - name: Set ethernet1/2 as static IP (Trusted)
    panos_interface:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      if_name: "ethernet1/2"
      mode: "layer3"
      ip: ["{pan_trusted_ip}/24"]
      enable_dhcp: false
      operation: "update"
      commit: False

  - name: Create route 'ILB'
    panos_static_route:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      name: 'ILB'
      destination: '1.1.1.0/24'
      nexthop: '10.0.0.1'    

  - name: Create route 'AppGW'
    panos_static_route:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      name: 'AppGW'
      destination: '1.1.1.0/24'
      nexthop: '10.0.0.1'   

  - name: Add ase-lib object
    panos_object:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      addressobject: 'ase-lib'
      address: '/32'
      address_type: 'ip-netmask'
      operation: 'add'

  - name: Set NTP
    panos_mgtconfig:
      ip_address: '{{ ansible_default_ipv4.address }}'
      username: '{{admin_username}}'
      password: '{{admin_password}}'
      ntp_server_primary: "time.windows.com"
      timezone: "Europe/London"   

  - name: Commit pending firewall changes
    panos_commit:
      ansible_default_ipv4.address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'