- name: pan-os-configuration
  hosts: all
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:

  - name: Set ethernet1/1 (Untrusted)
    panos_interface:
      ip_address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      if_name: "ethernet1/1"
      mode: "layer3"
      enable_dhcp: true
      operation: "update"
      commit: False

  - name: Set ethernet1/2 (Trusted)
    panos_interface:
      ip_address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'
      if_name: "ethernet1/2"
      mode: "layer3"
      enable_dhcp: true
      operation: "update"
      commit: False

  # - name: Create route 'ILB'
  #   panos_static_route:
  #     ip_address: '{{ ansible_default_ipv4.address }}'
  #     username: '{{ pan_username }}'
  #     password: '{{ pan_password }}'
  #     name: 'ILB'
  #     destination: '1.1.1.0/24'
  #     nexthop: '10.0.0.1'
  #     commit: False    

  # - name: Create route 'AppGW'
  #   panos_static_route:
  #     ip_address: '{{ ansible_default_ipv4.address }}'
  #     username: '{{ pan_username }}'
  #     password: '{{ pan_password }}'
  #     name: 'AppGW'
  #     destination: '1.1.1.0/24'
  #     nexthop: '10.0.0.1'
  #     commit: False   

  # - name: Add ase-lib object
  #   panos_object:
  #     ip_address: '{{ ansible_default_ipv4.address }}'
  #     username: '{{ pan_username }}'
  #     password: '{{ pan_password }}'
  #     addressobject: 'ase-lib'
  #     address: '/32'
  #     address_type: 'ip-netmask'
  #     operation: 'add'

  - name: Set NTP
    panos_mgtconfig:
      ip_address: '{{ ansible_default_ipv4.address }}'
      username: '{{admin_username}}'
      password: '{{admin_password}}'
      ntp_server_primary: "time.windows.com"
      timezone: "Europe/London"   

  - name: Commit pending firewall changes
    panos_commit:
      ip_address: '{{ ansible_default_ipv4.address }}'
      username: '{{ pan_username }}'
      password: '{{ pan_password }}'