- name: pan-os-configuration
  hosts: firewall
  connection: local
  gather_facts: False
  serial: 1

  roles:
  - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Calculate IPs
      set_fact:
        # Get network address from CIDR notation, convert to int, increment by 1, convert back to IPv4 format
        trusted_nexthop: "{{ (( trusted_address_prefix | ipaddr('network') | ipaddr('int') ) + 1) | ipaddr }}"
        untrusted_nexthop: "{{ (( untrusted_address_prefix | ipaddr('network') | ipaddr('int') ) + 1) | ipaddr }}"

    - name: Resolve trusted_destination_host
      when:
        (trusted_destination_host is defined) and (trusted_destination_host | trim != "")
      set_fact:
        trusted_destination_ip: "{{ lookup('dig', trusted_destination_host) }}"
    - name: (Debug) - trusted_destination_ip
      debug:
        var:
          trusted_destination_ip
    - name: Wait for API to be available on host
      uri:
        url: "https://{{ mgmt_ip }}/api"
        status_code: 200
        register: result
        until: result.status == 200
        retries: 600
        delay: 1
        validate_certs: false
        ignore_errors: yes

    - import_tasks: tasks/panos-baseline.yml

    - name: Commit firewall changes
      panos_commit:
        ip_address: '{{ mgmt_ip }}'
        username: '{{ username }}'
        password: '{{ password }}'
