- name: pan-os-configuration
  hosts: firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  tasks:

  - name: Configure NTP to 'time.windows.com'
    panos_mgtconfig:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      ntp_server_primary: "time.windows.com"
      timezone: "Europe/London"   

  - name: Set ethernet1/1 (Untrusted)
    panos_interface:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      if_name: "ethernet1/1"
      zone_name: "untrusted"
      mode: "layer3"
      enable_dhcp: true
      operation: "add"
      commit: False

  - name: Set ethernet1/2 (Trusted)
    panos_interface:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      if_name: "ethernet1/2"
      zone_name: "trusted"
      mode: "layer3"
      enable_dhcp: true
      operation: "add"
      commit: False

  - name: Create route 'protected-route'
    panos_static_route:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'protected-route'
      destination: '{{ trusted_destination_ip }}/32'
      nexthop: "{{ ((trusted_ip_prefix | ipaddr('int')) + 1) | ipaddr }}"
      commit: False    

  - name: Create route 'gateway-route'
    panos_static_route:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'gateway-route'
      destination: '0.0.0.0/0'
      nexthop: "{{ ((untrusted_ip_prefix | ipaddr('int')) + 1) | ipaddr }}"
      commit: False   

  - name: Add object 'protected-ip'
    panos_object:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'protected-ip'
      address: '{{ trusted_destination_ip }}/32'
      address_type: 'ip-netmask'
      operation: 'add'

  - name: Commit firewall changes
    panos_commit:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
