  - name: Configure NTP to 'time.windows.com'
    panos_mgtconfig:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      ntp_server_primary: "time.windows.com"
      timezone: "Europe/London"  
      commit: false