  - name: Set ethernet1/1 (Trusted)
    panos_interface:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      if_name: "ethernet1/1"
      zone_name: "trusted"
      mode: "layer3"
      enable_dhcp: false
      ip: ['{{ trusted_ip }}']
      operation: "add"
      state: 'present'
      commit: false

  - name: Set ethernet1/2 (Untrusted)
    panos_interface:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      if_name: "ethernet1/2"
      zone_name: "untrusted"
      mode: "layer3"
      enable_dhcp: false
      ip: ['{{ untrusted_ip }}']
      operation: "add"
      state: 'present'
      commit: false