  # Below 3 tasks are required per object to check existing state and either create or update
  - name: Check if object 'protected-ip' exists
    panos_object:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'protected-ip'
      address: '{{ trusted_destination_ip }}/32'
      address_type: 'ip-netmask'
      operation: 'find'
    register: protectedip
    ignore_errors: yes

  - name: Add object 'protected-ip' if it doesn't exist
    panos_object:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'protected-ip'
      address: '{{ trusted_destination_ip }}/32'
      address_type: 'ip-netmask'
      operation: 'add'
      commit: false
    when: protectedip is failed

  - name: Update object 'protected-ip' if it exists
    panos_object:
      ip_address: '{{ mgmt_ip }}'
      username: '{{ username }}'
      password: '{{ password }}'
      addressobject: 'protected-ip'
      address: '{{ trusted_destination_ip }}/32'
      address_type: 'ip-netmask'
      operation: 'update'
      commit: false
    when: protectedip is succeeded